apiVersion: v1
kind: Service
metadata:
  name: quicknook-frontend
  namespace: quicknook
spec:
  selector:
    app: quicknook-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
